---
title: "Uncoast Unconf Preparation"
subtitle: "R and git: macOS"
date: "2019-03-24"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# Welcome back!

--

### Last week: RStudio IDE and GitHub account

--

### This week: R and git installation

--

### Links are on the page hosting this video

### Reference: *Happy Git and GitHub for the useR*, Jenny Bryan et al.

### https://happygitwithr.com/

---
class: inverse

# Questions? Problems?

--
## If **you** are a part of Uncoast Unconf 2019:

--
### Check then, create a new GitHub issue:

`https://github.com/uncoast-unconf/uu-2019-day-zero/issues`

--
## OR

### Email Ian Lyttle at ian [dot] lyttle [at] se [dot] com

---

# Why are we doing this?

--

### We want all of our computers to be ready to collaborate

--

### Package-development tools work best using recent versions of R

--

### To move code to/from GitHub, we need git

---

# Goals for this week

### R

- what version do you have? In the **R console** pane:

```r
R.version.string
```

--

```
## [1] "R version 3.5.3 (2019-03-11)"
```

- if you have R 3.5.3, **you're done!** 

--

- if you have 3.4 <= R <= 3.5.2, up to you...

--

- if you have R < 3.4, **please update!**

--
  
- to get the latest version of R:
  - go to [https://cloud.r-project.org/](https://cloud.r-project.org/)
  - follow the *Download and Install R* link for macOS

- if you update more than a minor version, e.g. 3.4 -> 3.5, you have to reinstall your R packages

---

# Goals for this week

### git installation

- do you have git installed? In the **Terminal** pane:

```bash
git --version
```

--

```
git version 2.17.2 (Apple Git-113)
```

- if you get a response like this, **you're done!**

--

- if you do not get a response like this, your computer may offer to install *developer command-line tools*

  - we suggest you accept the offer
  - for our purposes you need only the command-line tools, (**not all of Xcode**)

---
class: inverse

# Questions? Problems?

--
## If **you** are a part of Uncoast Unconf 2019:

--
### Check then, create a new GitHub issue:

`https://github.com/uncoast-unconf/uu-2019-day-zero/issues`

--
## OR

### Email Ian Lyttle at ian [dot] lyttle [at] se [dot] com

---
class: inverse, center, middle

# Thanks, see you next week!