---
title: "Uncoast Unconf Preparation"
subtitle: "RStudio and GitHub"
date: "2019-03-17"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# Why are we doing this?

--

### We have only a few days together.

--

### We want you to be as ready as possible.

---

# If you are experienced with:

 - R
 - RStudio IDE
 - git
 - GitHub

--

### If you are happy with your set-up, no need to do anything to your computer.

--

### Please make sure you have access to your GitHub login and password.

---

# Goals for this week

--

### RStudio IDE

- what version do you have?
- if needed, update
- **verification**: check the terminal

--

### GitHub

- do you have an account? 
- if neded, let's get one
- do you have access to your login credentials?
- **verification**: say hello on a GitHub issue

---
class: inverse

# Questions? Problenms?

--
## If **you** are a part of Uncoast Unconf 2019:

--
### Check then, create a new GitHub issue:

-`https://github.com/uncoast-unconf/uu-2019-day-zero/issues`

--
## OR

### Email Ian Lyttle at ian [dot] lyttle [at] se [dot] com

---
class: inverse, center, middle

# Thanks, see you next week!

